dist: xenial

language: c

before_install:
  - sudo apt-get install -y fakeroot flex bison libelf-dev gettext autoconf autogen autopoint qemu-utils
  - tar xf 3pp/x86_64-linux-musl-cross.tgz
  - source setup.sh

script:
  - make -j $(cat /proc/cpuinfo | grep processor | wc -l)
