dist: xenial

language: c

before_install:
  - sudo apt-get install -y fakeroot
  - wget https://musl.cc/x86_64-linux-musl-cross.tgz
  - tar xf x86_64-linux-musl-cross.tgz
  - source setup.sh
  - env | grep ML_

script:
  - make -C examples/hello_world -j $(cat /proc/cpuinfo | grep processor | wc -l) build
